import AppKit
import NxlvKit

@MainActor final class GameView: NSView {
  var image: NSImage?; var engine: ModernLemmingsEngine?; var assets: ClassicMainDATAssets?; var palette: [ClassicRGBColor] = []; var onClick: ((Int)->Void)?
  override func draw(_ r:NSRect){ NSColor.black.setFill();r.fill(); guard let image else{return}; let scale=min(bounds.width/image.size.width,bounds.height/image.size.height); let size=NSSize(width:image.size.width*scale,height:image.size.height*scale); let origin=NSPoint(x:(bounds.width-size.width)/2,y:(bounds.height-size.height)/2); image.draw(in:NSRect(origin:origin,size:size)); guard let engine else{return}; let sx=size.width/engine.level.bounds.width, sy=size.height/engine.level.bounds.height; for l in engine.lemmings where l.state != .dead && l.state != .exiting { drawSprite(l, origin:NSPoint(x:origin.x+l.position.x*sx-8,y:origin.y+size.height-l.position.y*sy-16), scale:max(1, sx*2)) } }
  override func mouseDown(with e:NSEvent){ guard let engine=engine, let image=image else{return}; let scale=min(bounds.width/image.size.width,bounds.height/image.size.height); let size=NSSize(width:image.size.width*scale,height:image.size.height*scale); let origin=NSPoint(x:(bounds.width-size.width)/2,y:(bounds.height-size.height)/2); let p=e.locationInWindow; let sx=size.width/engine.level.bounds.width, sy=size.height/engine.level.bounds.height; let x=(p.x-origin.x)/sx,y=(origin.y+size.height-p.y)/sy; if let l=engine.lemmings.min(by:{hypot($0.position.x-x,$0.position.y-y)<hypot($1.position.x-x,$1.position.y-y)}),hypot(l.position.x-x,l.position.y-y)<24 {onClick?(l.id)} }
  func drawSprite(_ lemming: ModernLemming, origin: NSPoint, scale: CGFloat) {
    guard let assets, !palette.isEmpty else { return }
    let pose: ClassicLemmingPose = lemming.state == .falling || lemming.state == .floating ? .falling : .walking
    guard let animation = assets.animation(for: pose, direction: .right), !animation.frames.isEmpty else { return }
    let frame = animation.frames[Int(max(0, lemming.actionTime * 12).rounded()) % animation.frames.count]
    guard let rgba = try? frame.rgba(using: palette), let provider = CGDataProvider(data: rgba as CFData), let cg = CGImage(width: frame.width, height: frame.height, bitsPerComponent: 8, bitsPerPixel: 32, bytesPerRow: frame.width * 4, space: CGColorSpaceCreateDeviceRGB(), bitmapInfo: CGBitmapInfo(rawValue: CGImageAlphaInfo.last.rawValue), provider: provider, decode: nil, shouldInterpolate: false, intent: .defaultIntent) else { return }
    NSImage(cgImage: cg, size: NSSize(width: CGFloat(frame.width) * scale, height: CGFloat(frame.height) * scale)).draw(at: origin, from: .zero, operation: .sourceOver, fraction: 1)
  }
}

@MainActor final class AppDelegate:NSObject,NSApplicationDelegate {
  var window:NSWindow!; let view=GameView(frame:.zero); let picker=NSPopUpButton(frame:.zero); let status=NSTextField(labelWithString:"Loading Content…"); var campaign:ClassicCampaign?; var grounds=[Int:ClassicGroundSet](); var specials=[Int:ClassicSpecialGraphic](); var engine:ModernLemmingsEngine?; var timer:Timer?; var skill:ModernSkill = .builder; var progress = ModernCampaignProgress()
  func applicationDidFinishLaunching(_ n:Notification){let root=NSView();[picker,view,status].forEach{$0.translatesAutoresizingMaskIntoConstraints=false;root.addSubview($0)};let reload=NSButton(title:"Reload Content",target:self,action:#selector(load));reload.translatesAutoresizingMaskIntoConstraints=false;root.addSubview(reload);let pause=NSButton(title:"Pause",target:self,action:#selector(toggle(_:)));pause.translatesAutoresizingMaskIntoConstraints=false;root.addSubview(pause);let skills=NSStackView(views:ModernSkill.allCases.enumerated().map{let b=NSButton(title:$0.element.rawValue.capitalized, target:self, action:#selector(selectSkill(_:)));b.tag=$0.offset;return b});skills.orientation = .horizontal;skills.spacing = 4;skills.translatesAutoresizingMaskIntoConstraints=false;root.addSubview(skills);NSLayoutConstraint.activate([picker.leadingAnchor.constraint(equalTo:root.leadingAnchor,constant:16),picker.topAnchor.constraint(equalTo:root.topAnchor,constant:14),picker.widthAnchor.constraint(equalToConstant:330),reload.leadingAnchor.constraint(equalTo:picker.trailingAnchor,constant:10),reload.centerYAnchor.constraint(equalTo:picker.centerYAnchor),pause.leadingAnchor.constraint(equalTo:reload.trailingAnchor,constant:8),pause.centerYAnchor.constraint(equalTo:picker.centerYAnchor),status.leadingAnchor.constraint(equalTo:pause.trailingAnchor,constant:12),status.centerYAnchor.constraint(equalTo:picker.centerYAnchor),skills.leadingAnchor.constraint(equalTo:root.leadingAnchor,constant:16),skills.topAnchor.constraint(equalTo:picker.bottomAnchor,constant:8),view.leadingAnchor.constraint(equalTo:root.leadingAnchor),view.trailingAnchor.constraint(equalTo:root.trailingAnchor),view.topAnchor.constraint(equalTo:skills.bottomAnchor,constant:8),view.bottomAnchor.constraint(equalTo:root.bottomAnchor)]);picker.target=self;picker.action=#selector(changed);view.onClick={ [weak self] id in self?.assign(id)};window=NSWindow(contentRect:NSRect(x:0,y:0,width:1100,height:650),styleMask:[.titled,.closable,.resizable,.miniaturizable],backing:.buffered,defer:false);window.title="Lemmings — Native Modern Engine";window.contentView=root;window.center();window.makeKeyAndOrderFront(nil);timer=Timer.scheduledTimer(withTimeInterval:1.0/60.0,repeats:true){[weak self]_ in self?.tick()};load()}
  @objc func load(){let d=URL(fileURLWithPath:"/Users/veland/Lemmings/Content/lemming1.pc",isDirectory:true);do{let c=try ClassicCampaignDefinition.originalDOSLemmings.load(from:d);campaign=c;grounds=[:];specials=[:];for s in 0..<5{grounds[s]=try ClassicGroundSet.load(style:s,from:d)};for s in 0..<4{specials[s+1]=try ClassicSpecialGraphic.load(index:s,from:d)};if let data=UserDefaults.standard.data(forKey:"ModernCampaignProgress"),let saved=try? ModernCampaignProgress(encoded:data){progress=saved};picker.removeAllItems();c.levels.enumerated().forEach{picker.addItem(withTitle:"\($0.offset+1). \($0.element.rank) — \($0.element.level.title)")};picker.selectItem(at:0);changed()}catch{status.stringValue="Content error: \(error)"}}
  @objc func changed(){guard let c=campaign,picker.indexOfSelectedItem<c.levels.count else{return};let e=c.levels[picker.indexOfSelectedItem],l=e.level;do{guard let g=grounds[l.groundStyle]else{return};let r=try ClassicLevelRenderer.render(l,groundSet:g,specialGraphic:specials[l.specialStyle]);let p=CGDataProvider(data:r.rgba as CFData)!;let cg=CGImage(width:r.width,height:r.height,bitsPerComponent:8,bitsPerPixel:32,bytesPerRow:r.width*4,space:CGColorSpaceCreateDeviceRGB(),bitmapInfo:CGBitmapInfo(rawValue:CGImageAlphaInfo.last.rawValue),provider:p,decode:nil,shouldInterpolate:false,intent:.defaultIntent)!;view.image=NSImage(cgImage:cg,size:NSSize(width:r.width,height:r.height));var t=ModernTerrain(bounds:ModernRect(x:0,y:0,width:Double(r.width),height:Double(r.height)));let m=[UInt8](r.solidMask);for y in 0..<r.height{var s:Int?;for x in 0...r.width{let on=x<r.width && m[y*r.width+x] != 0;if on && s==nil{s=x};if !on,let a=s{t.addSolid(ModernRect(x:Double(a),y:Double(y),width:Double(x-a),height:1));s=nil}}};let inventory=l.skills.reduce(into:[ModernSkill:Int]()){ result, entry in if let mapped=ModernSkill(rawValue:entry.key.rawValue){result[mapped]=entry.value} };let ml=ModernLevel(bounds:ModernRect(x:0,y:0,width:Double(r.width),height:Double(r.height)),spawn:ModernPoint(x:Double(r.entrances.first?.x ?? 80),y:Double(r.entrances.first?.y ?? 80)),exit:ModernRect(x:Double(r.width-100),y:100.0,width:80.0,height:50.0),totalLemmings:l.lemmingCount,requiredToSave:l.saveRequirement,spawnInterval:0.5,terrain:t,skillInventory:inventory);engine=ModernLemmingsEngine(level:ml);view.engine=engine;status.stringValue="\(e.rank) \(e.number) • Modern engine"}catch{status.stringValue="Render error: \(error)"}}
  func tick(){if view.assets == nil { let d=URL(fileURLWithPath:"/Users/veland/Lemmings/Content/lemming1.pc",isDirectory:true); view.assets=try? ClassicMainDATAssets.load(from:d); if let ground=grounds[0], let p=try? ClassicLemmingPalette.inLevelVGA(terrainPalette:ground.terrainPalette) { view.palette=p } };guard var e=engine else{return};e.update(deltaTime:1.0/60.0);engine=e;view.engine=e;if e.isComplete{let index=picker.indexOfSelectedItem;progress.record(levelIndex:index,saved:e.saved,required:e.level.requiredToSave);if let data=try? progress.encoded(){UserDefaults.standard.set(data,forKey:"ModernCampaignProgress")};status.stringValue=e.didWin ? "Level complete — saved \(e.saved)/\(e.level.requiredToSave) • Press N for next" : "Level failed — saved \(e.saved)/\(e.level.requiredToSave) • Press R to retry"}}
  func restart(){changed()}
  func nextLevel(){guard let c=campaign else{return};let next=picker.indexOfSelectedItem+1;guard next<c.levels.count else{return};picker.selectItem(at:next);changed()}
  @objc func selectSkill(_ b:NSButton){skill=ModernSkill.allCases[b.tag];status.stringValue="Selected skill: \(skill.rawValue) — click a lemming"}
  @objc func toggle(_ b:NSButton){if timer == nil{timer=Timer.scheduledTimer(withTimeInterval:1.0/60.0,repeats:true){[weak self]_ in self?.tick()};b.title="Pause"}else{timer?.invalidate();timer=nil;b.title="Resume"}}
  func assign(_ id:Int){guard var e=engine else{return};if e.assign(skill,to:id){engine=e;view.engine=e}}
  func installKeyboardShortcuts(){NSEvent.addLocalMonitorForEvents(matching:.keyDown){[weak self] event in guard let self else{return event};switch event.charactersIgnoringModifiers?.lowercased(){case "n":self.nextLevel();case "r":self.restart();case "x":if var e=self.engine{e.nuke();self.engine=e;self.view.engine=e};case "escape":if let t=self.timer{t.invalidate();self.timer=nil}else{self.timer=Timer.scheduledTimer(withTimeInterval:1.0/60.0,repeats:true){[weak self]_ in self?.tick()}};default:return event};return nil}}
  override init(){super.init();installKeyboardShortcuts()}
  func applicationShouldTerminateAfterLastWindowClosed(_ s:NSApplication)->Bool{true}
}
let app=NSApplication.shared;let delegate=AppDelegate();app.delegate=delegate;app.setActivationPolicy(.regular);app.run()
